### ISSUE TITLE
[Crash 1.19.2] Crash when placing a Crate close to a Wireless Charger. (from @Wireless Chargers).

### ISSUE THREAD

**Issue by Gbergz** [AbsolemJackdaw/AppleCrates#11]
**Version Info**
- Minecraft: 1.19.2
- Apple Crate: [2.8.1](https://www.curseforge.com/minecraft/mc-mods/apple-crates/files/4017032)
- Wireless Chargers: [1.0.6b](https://www.curseforge.com/minecraft/mc-mods/wireless-chargers/files/3871937)

**Steps to Reproduce**
1.Place a wireless charger.
2. Then place an Apple Crate beside it or in the range of it.
3. Crash.

**Crash report (~/logs/latest.log)**
https://gist.github.com/Gbergz/ae68eaa30f6a4ba13ed0815cd79e2d2b

**More info here**
https://github.com/SuperMartijn642/WirelessChargers/issues/13

**Comment by AbsolemJackdaw** [comment]
fixed in 46d35c27927cbe05d35530836c6fe17eb2649b42

**Comment by Gbergz** [comment]
thank you for the swift fix!
