### ISSUE TITLE
Mixin conflict? fabric 1.19.2

### ISSUE THREAD

**Issue by AnomalousDeity** [AbsolemJackdaw/AppleCrates#13]
Applecrates has a issue with Mixins with the mod Scaffold forever.
![Untitled](https://user-images.githubusercontent.com/91780401/198420046-bad471a2-2066-4187-87d6-7e25bba6e624.png)

**Comment by AbsolemJackdaw** [comment]
allthough applecrates doesnt use mixins, the path to the mixin folder that comes with the mod is probably borked. 
I'll fix it, should be an easy fix.

this however also means scaffold's forgot to edit their own modid into their mixin json. you should probably report to them too

**Comment by AbsolemJackdaw** [comment]
new version has been uploaded !
