### ISSUE TITLE
Illegal Access Error?

### ISSUE THREAD

**Issue by MoonWillow333** [AbsolemJackdaw/AppleCrates#15]
So every time I try to place a crate, it gives me this error:

The game crashed whilst exception ticking world
Error: java.lang.IllegalAccessError: class jackdaw.applecrates.container.SimpleContainerNBT tried to access private field net.minecraft.class_1277.field_5828 (jackdaw.applecrates.container.SimpleContainerNBT and net.minecraft.class_1277 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @21a947fe)

I'm not too sure how to go about fixing it, if needed I can provide the full crash report. I looked around and couldn't find a real way to fix it.

**Comment by AbsolemJackdaw** [comment]
Are you using quilt ?

**Comment by MoonWillow333** [comment]
> Are you using quilt ?

Oh shoot I forgot to mention I'm using Fabric, 1.19.

**Comment by AbsolemJackdaw** [comment]
Weird. Probably a version difference issue

**Comment by MoonWillow333** [comment]
Aaah shoot, so in other words should I update to 1.19.2?

**Comment by AbsolemJackdaw** [comment]
The mod has been coded under 14.9, 0.60.0 for 1.19.2
What loader are you using ?

**Comment by MoonWillow333** [comment]
Fabric loader 0.14.8. That's probably why then. 
Thank you so much for the help, I couldn't find a clear answer anywhere for fabric but this helped a lot. :)
