### ISSUE TITLE
Suggestion. paystation

### ISSUE THREAD

**Issue by GreenForzeGaming** [AbsolemJackdaw/AppleCrates#17]
a paystation for time in redstone. so you put a item in for payment and you recive that time in a redstone signal. cool for entering dorrs or contraptions for players ^_^

**Comment by AbsolemJackdaw** [comment]
I like the idea, but I dont feel like it fits the crate model theme. 
To prevent expanding the mod in a direction that I dont envision I'm not going to add this to AppleCrates. 
lovely idea though. could be a fun standalone mod!
