### ISSUE TITLE
minecraft can't launch when both apple crates and structory: towers are in the mods folder

### ISSUE THREAD

**Issue by kuba26038** [AbsolemJackdaw/AppleCrates#19]
i got the issue when i loaded Structory_Towers_1.19_v1.0.1 alongside Apple Crates-forge-1.19.2-2.9.0. the game couldn't load, and the log file was created only partially. no clue why.

**Comment by ChromaPIE** [comment]
Having the same issue. Log: https://paste.ee/p/4wXh3

**Comment by AbsolemJackdaw** [comment]
Looks like a Fabric issue. fabric is going to be made soon(tm) and some residue code is already present.
for the next release, i'll make sure to clean the folder space up

**Comment by AbsolemJackdaw** [comment]
Hi,
It's been a while.
I apologise for the delay. I am picking modding back up but the paste of the log seems to have expired. 
With my previous comment I shall try to find the concerning issue and fix it

**Comment by AbsolemJackdaw** [comment]
updates were made and the code was cleaned. 
if the issue persists, feel free to reopen the issue
