### ISSUE TITLE
Can't sell mobs inside supplementaries cages

### ISSUE THREAD

**Issue by shannonr** [AbsolemJackdaw/AppleCrates#21]
Mobs captured inside supplementaries cages can not be sold, the trade item is in stock (grey arrow with no red cross) but when you use the trade button or place your trade item into the payment slot, the item doesn't appear to buy.

[image](https://imgur.com/a/kHKiTb4)

Thanks for you work on this mod, it helps give a real community feel to the server I play on.

**Comment by AbsolemJackdaw** [comment]
Thank you for your report!
Currently on a break, I'm going to have a hard time fixing this immediately, but I will be back at one point. 

This might be an NBT issue. 
I can't remember from the top of my head, but the item you are trying to sell may not match the items in stock in the crate. The comparison may be on NBT and the entity stocked/saved in the item NBT may be different from another entity saved in the other item's NBt, effectively making them too different to be considered the same item.

**Comment by AbsolemJackdaw** [comment]
yeah this is an nbt issue, 
to make sure you are always selling the same item and all items can stack if needed, the crate trading checks for the NBT tag. 
This means that other mods saving an entire entity to the NBT of an item will trip the system, as no entities are the same; For instance, every entity has a different ID. 

I would suggest reporting this also to Supplementairy Cages. 
If the author believes it is still an issue on my end, I hope we can resolve it together.
