### ISSUE TITLE
Easy Repeatable Duplication Glitch

### ISSUE THREAD

**Issue by StormCountTwo** [AbsolemJackdaw/AppleCrates#22]
Here is a [Demonstation](https://imgur.com/K4K6Aie) of how to reproduce the duplication glitch. This also works in a multiplayer server. 

In case the link doesn't work:
The jist of it is that if a buyer has items in the buying GUI & their inventory is full, then when they close the GUI the items that was in the GUI will drop to the ground AND remain in the GUI, effectively duping itself.

**Comment by AbsolemJackdaw** [comment]
woops. 
i'll fix this when I can
