### ISSUE TITLE
Rework the UI

### ISSUE THREAD

**Issue by AbsolemJackdaw** [AbsolemJackdaw/AppleCrates#26]
Current UI sucks donkeydick.
please rework and mind the UX.

**Comment by VirtualGaming1** [comment]
At first when I read the comment, I thought it was just a random rude user until i look above the comment

**Comment by AbsolemJackdaw** [comment]
new owner interface is settled. 
![image](https://github.com/user-attachments/assets/e5b5ded2-996f-4a64-b948-d7f9b7639ef9)

looking to adjust the enduser screen next

**Comment by AbsolemJackdaw** [comment]
UI has been changed
