### ISSUE TITLE
Items Not Rendering in Latest Version

### ISSUE THREAD

**Issue by irish-brigid** [AbsolemJackdaw/AppleCrates#33]
I know there's a closed issue for this, but I'm on 1.19.2 using the 2.12.1 version of the mod and I do not see any items in the crates, either mod items of vanilla.

I'm using Embeddium 0.3.18.1, Occulus 1.6.9, and Sildur's Vibrant Shaders Lite v1.166 in case that's relevant. I've turned on Forge's experimental render pipeline.

**Comment by AbsolemJackdaw** [comment]
I have no clue if 2.13.0 fixed it, but I added a patch that fixes slot issues when updating from an old version to a new version of applecrates. 
if you have a backup of your world (which you should make every time you update a mod) I'd advise to restore it, and download the latest version (2.13.0)
If it is rendering related because of graphics cards  and /or vr things, i may need to double check.

pelase let me know if 2.13.0 fixed anything for you

**Comment by irish-brigid** [comment]
I don't have a backup. Not even sure how to make a backup of a Minecraft save. Anyway, I use the Curse Forge launcher, which notified me there was an update. I updated, opened the world, and still nothing in the crates.

Anyway, I'm on Windows 10 (64 bit) with an NVIDIA GeForce GTX 1050 Ti GPU, if that helps. I don't have VR.

Oh, I also tried it with the shader turned off and still nothing, so it isn't the shader.

**Comment by AbsolemJackdaw** [comment]
Can you use the command /data get block <x y z> on one of the crates and can you post a screenshot of the result? 

_if you point your cursor to a crateblock, you can autofill the coordinates with the tab key_

I suspect crate saves got borked between updates, as 2.11.x contains [breaking changes.](https://www.curseforge.com/minecraft/mc-mods/apple-crates/files/5746606).

Confirming what the data in the crate looks like will determine wether it is an NBT issue, or a render issue.

**Comment by irish-brigid** [comment]
I should. Here goes.

![2024-10-06_09 27 27](https://github.com/user-attachments/assets/286cce7a-61bd-4548-a504-1e055f194089)

**Comment by AbsolemJackdaw** [comment]
That looks like a crate that you just placed. it that possible? 
If this crate was placed before, then the stored trade has effectively been erased by the update.

**Comment by irish-brigid** [comment]
It is. I'd removed all the crates and then added one back after the mod update.

Ah! I messed around with the GUI and it seems having contents isn't enough. I have to actually set up a trade. I'm on single player, so I hadn't bothered with that part of the mod. I just really like how it looks for my village market build.

**Comment by AbsolemJackdaw** [comment]
Glad we sorted it out! 
If you have any other questions, feel free to open a ticket, or join us on Discord!

**Comment by irish-brigid** [comment]
Thanks! I feel kinda silly, but I didn't see anything about the contents only appearing after the trade is set up in the mod info.
