### ISSUE TITLE
Broken Mineable/Axe Block Tag

### ISSUE THREAD

**Issue by WenXin20** [AbsolemJackdaw/AppleCrates#4]
Apple Crates v1.2.0
Minecraft v1.18.2

The block tag `minecraft:mineable/axe` currently is broken if botania, byg, malum, etc. is not installed. The below format will prevent any errors if one of the compat mods are not installed.

```
{
  "replace": false,
  "values": [
    { "id": "applecrates:biomesoplenty_mahogany_crate", "required":false },
    { "id": "applecrates:byg_embur_crater", "required":false }
  ]
}
```

**Comment by AbsolemJackdaw** [comment]
thanks for the tip,  i will fix this asap

**Comment by WenXin20** [comment]
Np, thanks!
