### ISSUE TITLE
Items not rendering in crate

### ISSUE THREAD

**Issue by magsum** [AbsolemJackdaw/AppleCrates#5]
![image](https://user-images.githubusercontent.com/106218980/175266958-9ef6562f-3c38-4bde-962c-0b9659fa3c46.png)

**Comment by magsum** [comment]
![image](https://user-images.githubusercontent.com/106218980/175267119-e55b433e-494c-4b8b-87c7-19482b918f52.png)

**Comment by AbsolemJackdaw** [comment]
Hi ! thanks for the report !
Do you happen to have Optifine installed?  
if you do not, are you using the API to make a mod compatiblity ? (i see night shade crate)
or is this from the included support for the mods ?

**Comment by magsum** [comment]
this happens in all the crates. im not sure what adds auto compatibility with your recipes, though. i am using Rubidium mainly for performance. i am in 1.18.2.

**Comment by AbsolemJackdaw** [comment]
very weird.
I'll be doing some testing to see what is going on.
Do you happen to have a log to attach ? latest.log would be nice

**Comment by magsum** [comment]
No problem. See if it is any use to you.
[latest.log](https://github.com/ArtixAllMighty/AppleCrates/files/8966813/latest.log)

**Comment by AbsolemJackdaw** [comment]
> [23Jun2022 17:47:16.656] [modloading-worker-0/INFO] [mixin/]: Mixing MixinItemRenderer from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.client.renderer.entity.ItemRenderer

only thing i found in the log that may be relevant. 
will check into it on my end too

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/175298504-08c728a1-eec1-400d-98bd-846980b9db97.png)
![image](https://user-images.githubusercontent.com/3628535/175298528-13e47a29-3ab0-49e4-b08c-3efd31e1ef00.png)
![image](https://user-images.githubusercontent.com/3628535/175298973-64a550d9-3df8-4a09-834d-387bc0ddb09f.png)
  
![image](https://user-images.githubusercontent.com/3628535/175299155-42242679-f7c9-49a6-8669-fcc8fd6f74b0.png)
![image](https://user-images.githubusercontent.com/3628535/175299191-fe7b9c70-39cf-48d7-abc3-97c687c8b2f1.png)

just launched the 1.18.2 version with B.Y.G and I seem to personally be running into an issue where it cannot find the mod support models to render. But even though the models arent found and not rendering, the items are definitly rendering.

I'm going to have to ask you to makea  backup copy of your world, or a new one, and start testing by removing mods one by one, to see which one is stopping the items from rendering. my first guess would be enigmaticlegacy, if not , rubidium.

**Comment by RFKreborn** [comment]
I'm having the same issue with the item renders in the box with 1.18.2 with version 1.2.1 of apple crates. There is also a render issue with the crates butt up against blocks.
![2022-07-12_20 16 52](https://user-images.githubusercontent.com/103884609/178622630-81846438-a943-49cb-ab03-ec6587bec491.png)
[latest.log](https://github.com/ArtixAllMighty/AppleCrates/files/9097813/latest.log)

**Comment by AbsolemJackdaw** [comment]
have you guys got optifine installed by any chance?

**Comment by AbsolemJackdaw** [comment]
what version of forge are you using ? 
there's also a rendering pipeline you can activate

**Comment by AbsolemJackdaw** [comment]
you can activate the forge pipeline to resolve the black weird shadow
its in the config folder

![image](https://user-images.githubusercontent.com/3628535/179241167-0f33480f-ac7e-4647-b8b8-b267d89ccd02.png)

**Comment by TheCrispyBarrett** [comment]
I have the issue of the items not rendering either, and I do have optifine.  Is that not compatible?

**Comment by AbsolemJackdaw** [comment]
optifçne is known to kill regular working rendering in mods yes.
it hasnt been really well comaptible with mods ever sicne 1.17. they added some high level changes that affect common vanilla code that might be used by mods, and it is clsoed source, so i can't try and make compatibility

**Comment by RFKreborn** [comment]
I don't have optifine, because it causes issues with too many mods. I'm on 1.18.2 with version 1.2.1 of crates. Sorry for the late reply.

**Comment by AbsolemJackdaw** [comment]
no problem.
have you got anything else installed ?

**Comment by RFKreborn** [comment]
Close to 200 mods, I've been trying to go through and see which ones are conflicting. It's odd, because sometimes the items will render, but the others won't. Even when i didn't have any other mods installed they wouldn't render.  Also, some of the tinker construct crates have broken textures.

**Comment by AbsolemJackdaw** [comment]
the textures are normally just the ones from the mod that are used. i'm currently trying an install out of dev to see if i can reproduce the error, but i'm not even able to make the compat trigger ._.

**Comment by RFKreborn** [comment]
That's odd. Ok, I got them semi-working ish. I set up a shop, but i have to relog in the world to trigger the textures to show.

**Comment by AbsolemJackdaw** [comment]
sounds like a desync issue ... I'm looking into 1.19 at the moment, i hope i can backport the fixes. shouldn't be too hard, if i manage to find the issue

**Comment by AbsolemJackdaw** [comment]
I found the issue.
1.19 will have it fixed. it was indeed a desync issue. 
1.18 will have the fix too, if i can get it to compile

**Comment by AbsolemJackdaw** [comment]
https://www.curseforge.com/minecraft/mc-mods/apple-crates/files/3882862 1.18.2
https://www.curseforge.com/minecraft/mc-mods/apple-crates/files/3882850 1.19

**Comment by RFKreborn** [comment]
Works for 1.18.2! Thank you, king.
