### ISSUE TITLE
Throwing a bunch of errors on server

### ISSUE THREAD

**Issue by mimi-min** [AbsolemJackdaw/AppleCrates#6]
Hello! 

Thank you for your work on this cute mod!

I'm not sure if this is game-breaking (I'm still working on getting the server to work...) but whenever I have Apple Crates loaded, I get bombarded with errors like these: https://pastebin.com/gFSvQkZb

The server will still run, but it's hard to keep track of the logs when this floods the console every time.

Do you think this is possible to fix?

Thank you!

**Comment by AbsolemJackdaw** [comment]
Sorry, I read this a while ago and never answered ! 

The errors are for the build in support for the other mods. The errors are about json files for blocks not being found, but its nothing bad, you can ignore them.
