### ISSUE TITLE
Feature Request: Potential hopper interaction(?)

### ISSUE THREAD

**Issue by forthwist** [AbsolemJackdaw/AppleCrates#7]
**Problem**:  I have crates all over my server at various farms, stalls, etc., and going around checking each one for sales is a big pain.
**Potential solution**: Payments can be pulled out via hopper into an ender chest.
**New problem**: Hoppers could be a security work around that allows people to take your profits.

Thoughts:
On my server we're a friendly/polite bunch and the hopper issue wouldn't be a problem, so maybe a config option?  I have no idea.  It would just be nice to be able to automatically pool my payments into something centralized like an enderchest.

**Comment by AbsolemJackdaw** [comment]
Hoppers into enderchest is not possible. Enderchests do not have an inventory. If your goal is centralized storage you will probably have to need another mod that teleports items between chests or something

I could add hopper support and will be looking into it either way, but I can't promise anything.
The way the payout is stored is trough nbt and hoppers only interact with slots and I dont know if I can split the stacks up with the stored value to put the correct stack in a hopper

**Comment by forthwist** [comment]
Oh, I've been using modded ender chests, didn't even realize that wasn't a thing in vanilla, oops!    Regardless, I have zero expectation here--some kind of inventory interaction/automation would be nice, but not necessary.  The mod is awesome as is and we've been really enjoying the crates on our server.  :)

**Comment by AbsolemJackdaw** [comment]
given the payment slot is unlimited, would you be happy with an auto refill ? 
i'm having to pick between interactions, and I was thinking automatic input would be more interesting then output.

can i have your two cents on this idea ?

**Comment by AbsolemJackdaw** [comment]
https://www.curseforge.com/minecraft/mc-mods/apple-crates/files/4017004

enjoy !!
