### ISSUE TITLE
[1.19.2] Shadow renders too dark on crates

### ISSUE THREAD

**Issue by Illios42** [AbsolemJackdaw/AppleCrates#8]
Hey, love this mod but when testing it out (v.2.7.1), it appears there is an issue with how the shadows render on the crates. Also happens with the Plenty Crates Addon for me.
I am using Optifine (client) and Starlight (server) so that could play a part in that (?) but I never had issues with them for any other mod like this. See the pic below for what it looks like:

![2022-09-21_11 02 48](https://user-images.githubusercontent.com/101580687/191464072-3ba08bdf-6d06-4b22-8bd4-cc5dfb0c9abd.png)
![2022-09-21_11 02 56](https://user-images.githubusercontent.com/101580687/191464141-539628ca-2738-47dc-a48c-4703c601a4c5.png)

**Comment by AbsolemJackdaw** [comment]
There's an option to turn on forge's rendering fix in their configuration file, located in the install directory. 
the file is called forge-client.toml

the value to change is this one : 

> 	#Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	forgeLightPipelineEnabled = true

**Comment by Illios42** [comment]
Interesting, like I said, first time I have this issue. Will try this out and let ya know if it works

**Comment by AbsolemJackdaw** [comment]
any update?

**Comment by AbsolemJackdaw** [comment]
closing , flagged as resolved
