### ISSUE TITLE
[1.19.2 | Suggestion ] Make crates render more items the more you fill them

### ISSUE THREAD

**Issue by Illios42** [AbsolemJackdaw/AppleCrates#9]
Right now crates seem to cap at 2-3 rendered Items which seems a little empty for some items. Perhaps a progressive "filling" of the crate the more items are in storage would make it more immersive and also act as an indicator to buyers how much they would be able to buy with just one glance.

**Comment by AbsolemJackdaw** [comment]
I can make this a config option for people who want it enabled. 
would you want a random distribution of the items, or rather the crate filling up from the down to the top?

**Comment by Illios42** [comment]
I think making it look more organized goes well with it being a way for shop keepers to show of their goods, so rows from the bottom to the top would make sense I think

I appreciate the quick answer! Lovely mod otherwise

**Comment by AbsolemJackdaw** [comment]
functionality added, file uploaded. look for 2.9.0 for 1.19.2
